services:

  # ========== service hello-world
  # docker run -it --rm --name service-hello-world-v2 -e PORT=8083 -e MYSQL_CONN_STRING=root@tcp(service-mariadb:3306)/hello_world?parseTime=true -p 8083:8083 --network my-network hello-world-v2
  service-hello-world:
    build: ./hello-world
    environment:
      - MYSQL_CONN_STRING=root@tcp(service-mariadb:3306)/hello_world?parseTime=true
      - PORT=8083
    ports:
      - 8083:8083
    networks: 
      - my-network
    depends_on:
      - service-mariadb

  # ========== service mariadb
  # docker run --name service-mariadb -it -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -v C:/Users/novalagung/Desktop/docker-volume-example:/var/lib/mysql --network my-network mariadb:10.1
  service-mariadb:
    image: mariadb:10.1
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - D:/docker-volumes/hello-world:/var/lib/mysql
      - ./mariadb/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    ports:
      # not exposed outside the network
      - 3306
    networks: 
      - my-network

networks:
  my-network:
